### ISSUE TITLE
Coupler versurf mismatch within DistriPotent processing from XGC

### ISSUE THREAD

**Issue by Damilare06** [SCOREC/wdmapp_coupling#104]
I currently run the following:

`CPL` -> `gem-xgc` branch of  https://github.com/Damilare06/wdmapp_coupling.git
`XGC` -> `gemCouple` branch of https://github.com/Damilare06/XGC-User.git 
`GEM` -> `pgigem` branch of https://github.com/Damilare06/GEM-parallel-coupling

The coupler fails during processing the field values received from xgc within the `DistriPotentRecvfromXGC` [here](https://github.com/Damilare06/wdmapp_coupling/blob/8fb480e32021d03a49d08a4aecd8f46ef6b2e4bb/src/gemXgcDataproc.cc#L292).

`p3->thetaflx_ind_pot[i][j][k][h][0]` has a value of 209992536, while the last index of the `tmp` array only has a smaller dimension [here](https://github.com/Damilare06/wdmapp_coupling/blob/8fb480e32021d03a49d08a4aecd8f46ef6b2e4bb/src/gemXgcDataproc.cc#L255)

```
1418 2: 17: ABJ 2.1
1419 2: 4: ABJ 2.1
1420 2: 14: 14: receive xgc_field done
1421 2: 14: ABJ 2.0
1422 2: 3: ABJ 2.1
1423 2: 12: ABJ 2.1
1424 2: 1: ABJ 2.1
1425 2: 13: ABJ 2.1
1426 2: 5: ABJ 2.1
1427 2: 15: ABJ 2.1
1428 2: 2: ABJ 2.1
1429 2: 14: ABJ 2.1
1430 2: 16: ABJ 2.1
1431 2: 6: ABJ 2.1
1432 2: 8: ABJ 2.1
1433 2: 11: ABJ 2.1
1434 2: 10: ABJ 2.1
1435 2: 6: ABJ 2.2
1436 2: 6: ABJ 2.20 i: 0, j: 0, k: 0, h: 0, theta: 209992536 vs vers: 481, outside lagrange interpo
1437 2: 5: ABJ 2.2
1438 2: 5: ABJ 2.20 i: 0, j: 0, k: 0, h: 0, theta: 209992536 vs vers: 424, outside lagrange interpo
1439 2: 5: [a01n02:167788] *** Process received signal ***
1440 2: 5: [a01n02:167788] Signal: Segmentation fault (11)
1441 2: 5: [a01n02:167788] Signal code: Address not mapped (1)
1442 2: 5: [a01n02:167788] Failing at address: 0x7c143340
1443 2: 10: ABJ 2.2
1444 2: 10: ABJ 2.20 i: 0, j: 0, k: 0, h: 0, theta: 209992536 vs vers: 1149, outside lagrange interpo
1445 2: 10: [a01n03:60500] *** Process received signal ***
1446 2: 10: [a01n03:60500] Signal: Segmentation fault (11)
1447 2: 10: [a01n03:60500] Signal code: Address not mapped (1)
1448 2: 10: [a01n03:60500] Failing at address: 0xc05a9d90
1449 2: 10: [a01n03:60500] [ 0] [0x2000000504d8]
1450 2: 10: [a01n03:60500] [ 1] /gpfs/alpine/fus123/scratch/damilare/gem-xgc/cpl-pgi-build/test/gemxgc[0x10026da8]
1451 2: 10: [a01n03:60500] [ 2] 2: 1: ABJ 2.2
1452 2: 1: ABJ 2.20 i: 0, j: 0, k: 0, h: 0, theta: 209992536 vs vers: 200, outside lagrange interpo
1453 2: 1: [a01n02:167784] *** Process received signal ***
1454 2: 1: [a01n02:167784] Signal: Segmentation fault (11)
1455 2: 1: [a01n02:167784] Signal code: Address not mapped (1)
1456 2: 1: [a01n02:167784] Failing at address: 0xb6919cc0
```

**Comment by Damilare06** [comment]
Further investigation revealed that the `thetaflx_ind_pot` array was initialized to that value

```
   747 2: 2: ABJ 30, theta: 212089688
   748 2: 2: ABJ 30, theta: 212089688
   749 2: 2: ABJ 30, theta: 212089688
   750 2: 2: ABJ 30, theta: 212089688
   751 2: 2: ABJ 30, theta: 212089688
   752 2: 2: ABJ 30, theta: 212089688
   753 2: 2: ABJ 30, theta: 212089688
   754 2: 2: ABJ 30, theta: 212089688
   755 2: 2: ABJ 30, theta: 212089688
   756 2: 2: ABJ 30, theta: 212089688
   757 2: 2: ABJ 30, theta: 212089688
   758 2: 2: ABJ 30, theta: 212089688
   759 2: 2: ABJ 30, theta: 212089688
   760 2: 2: ABJ 30, theta: 212089688
   761 2: 2: ABJ 30, theta: 212089688
   762 2: 2: ABJ 30, theta: 212089688
```

**Comment by cwsmith** [comment]
@Damilare06 Interesting.  Where is `thetaflx_ind_pot` initialized?  Can you paste the link to the line(s) of code?

**Comment by Damilare06** [comment]
Its initialization can be found [here](https://github.com/Damilare06/wdmapp_coupling/blob/7233a1ca10643be3684720a16d12548e41450e06/src/importpart3mesh.cc#L596)

**Comment by jycheng1989** [comment]
I want to check whether it is the DIII-D case or not.
If so, the dimension of field and density is not the same for GEM and XGC, since the DIII-D case in the XGC side includes  the open field line region. Please check the original GEM-XGC coupling case and find the correct dimension.
@phyboyzhang @phyboyzhang @Damilare06

**Comment by cwsmith** [comment]
Hi @jycheng1989.  As I understand, we are testing has concentric flux surfaces ( 'cyclone' ?).  The input files are here:

https://github.com/phyboyzhang/testcases/tree/gem_summit_test

**Comment by jycheng1989** [comment]
> Hi @jycheng1989. As I understand, our test case has concentric flux surfaces ( 'cyclone' ?). The input files are here:
> 
> https://github.com/phyboyzhang/testcases/tree/gem_summit_test

I see. Thanks. @cwsmith

**Comment by phyboyzhang** [comment]
I will investigate this bug.

**Comment by phyboyzhang** [comment]
The problem is solved here:  https://github.com/phyboyzhang/wdmapp_coupling-1/tree/gemxgc2

**Comment by cwsmith** [comment]
for the record, it is this commit: https://github.com/phyboyzhang/wdmapp_coupling-1/commit/959e22a8c09fcc015a203f262021a710df6d49cf
