### ISSUE TITLE
test_twoClientOverlap: partitioning the server to 16 ranks

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/wdmapp_coupling#114]
Running the `test_twoClientOverlap` server with 16 ranks and following cpn file results in the assert `REDEV_ALWAYS_ASSERT(entToRank[ent] == owners[i]);` being triggered in append() in test_support.cpp:

https://github.com/SCOREC/wdmapp_coupling/blob/d17a306105a9f70de25cadbb8bd6145422d23c33/test/test_support.cpp#L159-L160

The failing check indicates that the model vertex and edge ownership, derived from the cpn file, isn't self consistent.

https://github.com/SCOREC/wdmapp_coupling/blob/d17a306105a9f70de25cadbb8bd6145422d23c33/test/test_support.cpp#L189

Thanks @philip-davis for reporting this.

```

58
1 0
2 0
3 0
4 0
5 1
6 1
7 1
8 1
9 1
10 2
11 2
12 2
13 2
14 2
15 2
16 3
17 3
18 3
19 3
20 3
21 3
22 4
23 5
24 5
25 6
26 6
27 7
28 7
29 8
30 9
31 9
32 10
33 11
34 11
35 12
36 12
37 12
38 12
39 12
40 12
41 13
42 13
43 13
44 13
45 13
46 14
47 14
48 14
49 14
50 14
51 14
52 15
53 15
55 15
57 15
58 15
```

**Comment by cwsmith** [comment]
A vtk written out before mesh element migration with the destination rank of each element attached as a tag seems looks OK.  

![destRanks0-8](https://user-images.githubusercontent.com/1024438/180866459-e5c1a8fd-77ec-4151-a5df-df9269e9cff9.png)
![destRanks9-15](https://user-images.githubusercontent.com/1024438/180866460-68f15b98-67a4-4f39-8686-14bd393181fa.png)


Given that, there is either a problem in the MPI send-recv of the element indices from rank 0

https://github.com/SCOREC/wdmapp_coupling/blob/9a5900a5bcee0031fa636606c21a91222e53fb3e/test/test_support.cpp#L220-L229

https://github.com/SCOREC/wdmapp_coupling/blob/9a5900a5bcee0031fa636606c21a91222e53fb3e/test/test_support.cpp#L246-L251

or, more likely, a bug in the(my) `Omega_h::migrate` function:

https://github.com/SCOREC/omega_h/blame/f58f1d97bfd01b9c16370366e3415ad177a3793a/src/Omega_h_mesh.cpp#L959-L970

**Comment by cwsmith** [comment]
https://github.com/SCOREC/wdmapp_coupling/commit/1973b4e96113f4d70e42d8b777bbca8a2afb7733 has a potential fix for the classification mismatch problem.  See the commit message for details.

A branch of redev containing a related change that eliminates unnecessary logic is here:
https://github.com/SCOREC/redev/commit/910cee87008ffa3ecfe76b1e00bcff66b13c6f5e

After the ranks of server compute the ownership of model entities associated with their part boundaries (in `test_support.cpp`), all the ownership info is gathered to server rank 0 in the `Redev::ClassPtn()` ctor, `Redev::Setup(...)` sends the partition info from server rank 0 to rank 0 on the clients, and then rank 0 on both the client and server broadcasts the partition info to the other ranks in the respective communicators.  With the above change to redev, and this sequence of communications, there *should* be no inconsistency between server/client ranks in the partition info (barring a memory error... etc.).

It isn't clear yet what is causing the assertion in `wdmcpl.h`.

**Comment by cwsmith** [comment]
Tests with 2, 4 and 8 rendezvous parts pass.  The added tests are here https://github.com/SCOREC/wdmapp_coupling/commit/c5aafca3695e423396a6d02f83655314c0e7061f and the input cpns here https://github.com/SCOREC/wdmapp_testcases/commit/09c25e8730921ab3a6ed69d896a654239653c639.

**Comment by jacobmerson** [comment]
Interesting. Is it possible that the ownership of that ring is getting messed up during the partition process?

**Comment by cwsmith** [comment]
Possibly, but I'm not seeing problems with it so far on the server side.  Given that, I think the problem is on the application/client side with the data behind the `GetRank()` query. 

The (sorted) gids received on rank 11 of the server are below:

```
rgids: 332, 335, 339, 379, 383, 395, 402, 405, 541, 675, 678, 686, 691, 801, 805, 813, 817, 1441, 1442, 1450, 1452, 1460, 1651, 1653, 1658, 1659, 1662, 1663, 1665, 1666, 1684, 1779, 1785, 1956, 1958, 1963, 1972, 1974, 2150, 2152, 2156, 2199, 2201, 2205, 2647, 2648, 2660, 2661, 2667, 2670, 2681, 2686, 2776, 2777, 2789, 2791, 2792, 2795, 3205, 3209, 3210, 3217, 3289, 3297, 3317, 3319, 3322, 3328, 3345, 4431, 4441, 4444, 4504, 4507, 4516, 4521, 4534, 4537, 4538,
```

The single mesh vertex classified on a geometric model vertex is not included in the set of received gids on server rank 11.

![overlapGids_vtxClass_rank11_](https://user-images.githubusercontent.com/1024438/184714629-ff166c2a-a0ce-4c4f-8cea-38a3d118d8e5.png)
 
 and here are the rank 11 received gids marked and labelled:
 
 
![overlapGids_rgids_rank11](https://user-images.githubusercontent.com/1024438/184714781-ccf13e02-8d3f-48f2-b618-74ff2e97889f.png)

**Comment by cwsmith** [comment]
The problem was resolved with https://github.com/SCOREC/wdmapp_coupling/commit/cbca4c1b9f69f8aaadccda8c097bab70d418ee6e and all tests are now passing.

A draft PR was just created; https://github.com/SCOREC/wdmapp_coupling/pull/117.  Once the debug stuff is removed up I'll make it a active PR (not a draft).

It adds the function `markServerOverlapRegion(...)` to mark mesh vertices in the overlap region following different ownership rules than the client(s).  The code has a comment block that explains it the difference:

https://github.com/SCOREC/wdmapp_coupling/blob/80a00a41923132ccdbbbbceb9d8fb2c6a74eefb3/test/test_proxy_coupling.cpp#L29-L43
