### ISSUE TITLE
The problem about the Fourier space spectrum 

### ISSUE THREAD

**Issue by phyboyzhang** [SCOREC/wdmapp_coupling#73]
The  subroutine in the module file [here](https://github.com/wdmapp/gene/blob/cbd16fb3661b30cb77c2091b91a6af5f46a4c3a7/src/coupling/planes_fourier_fftw.F90#L43) is posted here.
```
Subroutine to_fourier_y_only(inarr,outarr)
    Real,    Dimension(0:2*gdisc%nj0*res_fact-1,0:gdisc%li0/n_procs_y-1), intent(in) :: inarr
    Complex, Dimension(0:gdisc%nj0-1, 0:gdisc%li0/n_procs_y-1), intent(out) :: outarr
    Complex, Dimension(0:gdisc%nj0*res_fact, 0:gdisc%li0/n_procs_y-1) :: tmparr

    call sfftw_execute_dft_r2c(bplan_y_arb, inarr(0,0), tmparr(0,0))
    outarr=tmparr(0:gdisc%nj0-1,:)*facnny_arb

  end Subroutine to_fourier_y_only
```
The array outarr only inherits the first gdisc%nj0 elements of the first dimension in tmparr. Since in the new wdaapp/GENE, both "res_fact" and "n0_global" equal 4, the latter 3*gdisc%nj0 elements of the first dimension in  tmparr are thrown away, perhaps impacting the accuracy of the result.  It may be better to increase  nky0=16 to nky0=16*n0_global, so that the first gdisc%nj0*res_fact elements can be kept.

**Comment by cwsmith** [comment]
This appears to be resolved.  Please re-open if needed.
