### ISSUE TITLE
cpl sending Nan to XGC

### ISSUE THREAD

**Issue by Damilare06** [SCOREC/wdmapp_coupling#75]
At the 6th send loop, the coupler is observed to send invalid values to XGC and this bug is caught by the check [here](https://github.com/wdmapp/XGC-Devel/blob/rpi/XGC_core/coupling_core_edge_gene.F90#L238-L241) 

@phyboyzhang has said the latest modifications within the `szDev` branch should address this bug...

**Comment by phyboyzhang** [comment]
@Damilare06 Is this problem still here?

**Comment by phyboyzhang** [comment]
This problem was already solved by the new pr [here](https://github.com/wdmapp/gene/pull/13/commits/587d9f98880facb7481298e73d65ac02079da2d5).

**Comment by cwsmith** [comment]
Is this issue still present with our latest branches (in the scorec repo or a fork) of gene, xgc, and the coupler?

**Comment by Damilare06** [comment]
No it is not
