### ISSUE TITLE
seg fault on Rhea in coupler

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/wdmapp_coupling#77]
coupler version: fcd22e5 
gene version: https://github.com/wdmapp/gene/commit/1a5e1c77affb85a00e44f66d0fcb3e03f8d7bb2c
xgc version: https://github.com/wdmapp/XGC-Devel/commit/6bd3ad3fda4f4d37897dad338a308785a2c51fef
testcases version (using [run_externalCpl.yaml](https://github.com/SCOREC/testcases/blob/f15a37217a51d0ff467f0811b724b137982ee43a/run_1/rhea/run_externalCpl.yaml)): https://github.com/SCOREC/testcases/tree/f15a37217a51d0ff467f0811b724b137982ee43a
wdmapp-config version: (used to install xgc and effis, and the dependencies for gene and coupler) https://github.com/SCOREC/wdmapp-config/tree/728d07b8f711ffedf1206072a8326dfe199f82d6

On AiMOS we can execute one timestep of the cyclone test case (https://github.com/wdmapp/testcases/tree/4ae055ea046d354c9026ec54344dcd710f6ac20b/run_1/aimos) and exit all three executables without any obvious errors.

On Rhea, using gcc 8.4 and openmpi@3.1.4, running the cyclone case fails at this memory allocation:

https://github.com/SCOREC/wdmapp_coupling/blob/fcd22e5abdf1b78a5fec1e842b66496272cc95e0/src/importpart3mesh.h#L150

which is called from here during the first RK loop:
https://github.com/SCOREC/wdmapp_coupling/blob/fcd22e5abdf1b78a5fec1e842b66496272cc95e0/src/dataprocess.cc#L320

whose parent function `AssemDensiSendtoPart3(...)` is called from `cpl.cc` here:
https://github.com/SCOREC/wdmapp_coupling/blob/fcd22e5abdf1b78a5fec1e842b66496272cc95e0/test/cpl.cc#L136

The values of `vertnum` seem OK, 69 on ranks 0 and 1 and 1371 on ranks 2 and 3, so I suspect that the error is triggered by an adios failure.  As a sanity check, we can run on Rhea with BP4.  It isn't clear though if SST in-memory transfers are causing problems here.

For the record, the final output of each executable is attached.  [output.tar.gz](https://github.com/SCOREC/wdmapp_coupling/files/4866618/output.tar.gz).  Note, the coupler output contains multiple print statements that were not part of the coupler version above.  That modified version is here: https://github.com/cwsmith/wdmapp_coupling/commit/68a1032fa5a9ebac25dbacefaa9e7f53d88d02d3

From what I can tell, gene and xgc failures are a consequence of the coupler failing:

- gene: `adios2_open` fails when trying to open `cpl_field`.. which does not get written because the coupler fails https://github.com/wdmapp/gene/blob/1a5e1c77affb85a00e44f66d0fcb3e03f8d7bb2c/src/coupling/coupler_pproc.F90#L253
- xgc: fails while waiting for density from the coupler ... which does not get written because the coupler fails before sending density to XGC

@suchyta1 Do you see anything obviously concerning in the output?  The run directory on Rhea is here:
`/gpfs/alpine/phy122/scratch/cwsmith/testWdmCpl_manualCplBuild_3`

**Comment by phyboyzhang** [comment]
I met the similar problem on AiMOS  when I debug the code. The problem on AIMOS was already solved on AIMOS by restricting my_pez==0 here: https://github.com/phyboyzhang/gene/blob/dba61187c7c284df3db211414870400df627cbd9/src/coupling/XGC_grid.F90#L355
It's still due to the transpose of the processes of subcommunicator.

**Comment by jacobmerson** [comment]
Closing due to coupler rewrite.
