### ISSUE TITLE
The problem of building  gene@coupling on summit

### ISSUE THREAD

**Issue by phyboyzhang** [SCOREC/wdmapp_coupling#81]
The wdmapp and effis were installed successfully. And I tried to build gene@coupling  which was cloned from git@github.com:wdmapp/gene.git. I used "spack install  gene@coupling" for installing and "spack setup  gene@coupling" for setup. Then the error appears: 
```
==> Generating spconfig.py [gene@coupling%gcc@8.1.1~adios2~cuda~diag_planes~effis~futils+pfunit~wdmapp build_type=RelWithDebInfo cuda_arch=none perf=none arch=linux-rhel7-power9le/azwdeeo]
==> Error: No JSON object could be decoded
```

**Comment by germasch** [comment]
`spack install gene@coupling` should do all you need. `spack setup ...`  is an alternative to set things up for building gene yourself, but using the dependencies provided by spack. 

`spack setup` is out-of-date/unsupported, though it still mostly works. The error you're getting above can actually be safely ignored.

**Comment by phyboyzhang** [comment]
Yes. Thanks. At beginning, I tried to build gene@external_cpl, which is not included by gene/package.py. So I got that problem without spconfig.py generated. But after I switched to gene@coupling, I ignored to check whether spconfig.py exists, which exists indeed.
