### ISSUE TITLE
Invalid incoming buffer - ADIOS2

### ISSUE THREAD

**Issue by Damilare06** [SCOREC/wdmapp_coupling#90]
Hi Eric, I am running:

- the `develop` branch of this [coupler]( https://github.com/SCOREC/wdmapp_coupling)
- the `rpi` branch of [this](https://github.com/wdmapp/XGC-Devel) xgc-devel 
- the `rpi` branch of [this](https://github.com/phyboyzhang) gene 

When running the coupler with `Sst` mode, I get this output from the coupler as `xgc` attempts to read from it (before this, the `coupler` has successfully read multiple sst buffers from `gene`).

Using the `effis` submit setup I got 
```
 34 2: receive gene_density done                                                                         | 94 mype, start count2 0 2160 16 2160
 35 3: receive gene_density done                                                                         | 95 rank=2
 36 invalid format in incoming buffer                                                                    | 96 ../coupling/gene_density.bp
 37 ERROR:  One or more process (first noticed rank 0) terminated with signal 12                         | 97 creat engine for: gene_density
~                                                                                                        | 98 engine parameters are set
~                                                                                                        | 99 Shape 0 1=4320 16
~                                                                                                        |100 Shape 0 1=4320 16
~                                                                                                        |101 Shape 0 1=4320 16
~                                                                                                        |102 Shape 0 1=4320 16
~                                                                                                        |103 numiter,ranki densityfromGENE=0 0 (8.82229,-0.0714541)
~                                                                                                        |104 p3m3d.lj0*p3m3d.blockcount=1990816
~                                                                                                        |105 numiter,ranki densitytoXGC=0 0 259424 1990816
~                                                                                                        |106 numiter,ranki densityfromGENE=0 3 (28.0649,-0.0714279)
~                                                                                                        |107 p3m3d.lj0*p3m3d.blockcount=5130432
~                                                                                                        |108 numiter,ranki densitytoXGC=0 1 543136 5130432
~                                                                                                        |109 numiter,ranki densityfromGENE=0 2 (21.4586,0.0714541)
~                                                                                                        |110 p3m3d.lj0*p3m3d.blockcount=5130432
~                                                                                                        |111 numiter,ranki densitytoXGC=0 1 543136 5130432
~                                                                                                        |112 numiter,ranki densityfromGENE=0 1 (11.5387,0.0714279)
~                                                                                                        |113 p3m3d.lj0*p3m3d.blockcount=1990816
~                                                                                                        |114 numiter,ranki densitytoXGC=0 0 259424 1990816
codar.workflow.stderr.coupler                                                          1,1            All codar.workflow.stdout.coupler                   
```

Thinking it was an `effis` issue, I switched to a regular submit file and I got the same error

```
2: 3: p3m3d.lj0*p3m3d.blockcount=5130432                                                                 │1: 0:  background elec charge
2: 3: 0.0 ABJ                                                                                            │1: 0:  End of setup
2: 3: 0.1 ABJ                                                                                            │1: 0:  main loop started
2: 3: 0.2 ABJ                                                                                            │1: 0:  - do loop start
2: 3: 0.3 ABJ                                                                                            │1: 0: step,trigger,ratio,# of ion      1     1.1000     1.0000      512000000
2: 0: invalid format in incoming buffer                                                                  │1: 0: step,f0(ratio,max)    1    -1.0000     0.0000
Could not read jskill result from pmix server                                                            │Could not read jskill result from pmix server
                                                                                                         │
```

The coupler still fails the moment `xgc` connects.

When I turn on `SstVerbose`, I get this output just before the coupler fails;

```
529 2: 3: Writer 3 (0x4d531770): Opening Stream "../coupling/cpl_density.bp"
5530 2: 3: Writer 3 (0x4d531770): Stream "../coupling/cpl_density.bp" waiting for 1 readers
5531 2: 0: Writer 0 (0x454f34e0): Opening Stream "../coupling/cpl_density.bp"
5532 2: 0: Writer 0 (0x454f34e0): Writer stream params are:
5533 2: 0: Param -   RegistrationMethod=File
5534 2: 0: Param -   RendezvousReaderCount=1
5535 2: 0: Param -   QueueLimit=0 (unlimited)
5536 2: 0: Param -   QueueFullPolicy=Block
5537 2: 0: Param -   DataTransport=rdma
5538 2: 0: Param -   ControlTransport=sockets
5539 2: 0: Param -   NetworkInterface=(default)
5540 2: 0: Param -   ControlInterface=(default to NetworkInterface if applicable)
5541 2: 0: Param -   DataInterface=(default to NetworkInterface if applicable)
5542 2: 0: Param -   CompressionMethod=None
5543 2: 0: Param -   CPCommPattern=Min
5544 2: 0: Param -   MarshalMethod=BP
5545 2: 0: Param -   FirstTimestepPrecious=False
5546 2: 0: Param -   IsRowMajor=1  (not user settable)
5547 2: 0: Param -   OpenTimeoutSecs=480 (seconds)
5548 2: 0: Param -   SpeculativePreloadMode=Auto
5549 2: 0: Param -   SpecAutoNodeThreshold=1
5550 2: 0: Param -   ControlModule=select
5551 2: 0: Writer 0 (0x454f34e0): Stream "../coupling/cpl_density.bp" waiting for 1 readers
5552 2: 0: invalid format in incoming buffer
```

Below is a copy of the  run scripts I used in both cases

[runScripts.zip](https://github.com/SCOREC/wdmapp_coupling/files/5075643/runScripts.zip)

Please note that my post-doc @phyboyzhang can run successfully with the regular job submission.

Moreover, I run the jobs from a clean terminal with these modules 

```
[damilare@login2.summit run_1]$ module li

Currently Loaded Modules:
  1) xl/16.1.1-5                      4) xalt/1.2.0              7) DefApps
  2) spectrum-mpi/10.3.1.2-20200121   5) lsf-tools/2.0           8) tmux/2.2
  3) hsi/5.0.2.p5                     6) darshan-runtime/3.1.7   9) git/2.20.1
```

Your help would be appreciated

**Comment by Damilare06** [comment]
@suchyta1 This is a gentle reminder

Also, when I try uninstalling my spack packages, I get the error;

```
==> [2020-08-17-08:41:21.055303, 88496] READ LOCK (database): /autofs/nccs-svm1_home1/damilare/dev/spack/opt/spack/.spack-db/lock[0:0] [Releasing] 
==> [2020-08-17-08:41:21.055619, 88496] READ LOCK (database): /autofs/nccs-svm1_home1/damilare/dev/spack/opt/spack/.spack-db/lock[0:0] [Released at 08:41:21.055593] 
==> [2020-08-17-08:41:23.176206, 88496] WRITE LOCK (py-setuptools-scm): /autofs/nccs-svm1_home1/damilare/dev/spack/opt/spack/.spack-db/prefix_lock[3519323708714225209:1] [Releasing] 
==> [2020-08-17-08:41:23.176875, 88496] WRITE LOCK (py-setuptools-scm): /autofs/nccs-svm1_home1/damilare/dev/spack/opt/spack/.spack-db/prefix_lock[3519323708714225209:1] [Released at 08:41:23.176844] 
Traceback (most recent call last):
  File "/ccs/home/damilare/dev/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/lib/spack/spack/main.py", line 763, in main
    return _invoke_command(command, parser, args, unknown)
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/lib/spack/spack/main.py", line 488, in _invoke_command
    return_val = command(parser, args)
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/lib/spack/spack/cmd/uninstall.py", line 348, in uninstall
    uninstall_specs(args, specs)
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/lib/spack/spack/cmd/uninstall.py", line 323, in uninstall_specs
    do_uninstall(env, uninstall_list, args.force)
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/lib/spack/spack/cmd/uninstall.py", line 225, in do_uninstall
    item.do_uninstall(force=force)
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/lib/spack/spack/package.py", line 1754, in do_uninstall
    Package.uninstall_by_spec(self.spec, force)
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/lib/spack/spack/package.py", line 1726, in uninstall_by_spec
    spack.hooks.pre_uninstall(spec)
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/lib/spack/spack/hooks/__init__.py", line 59, in __call__
    hook(*args, **kwargs)
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/lib/spack/spack/hooks/extensions.py", line 18, in pre_uninstall
    if pkg.is_activated(view):
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/lib/spack/spack/package.py", line 1023, in is_activated
    exts = extensions_layout.extension_map(self.extendee_spec)
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/lib/spack/spack/directory_layout.py", line 430, in extension_map
    return self._extension_map(spec).copy()
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/lib/spack/spack/directory_layout.py", line 457, in _extension_map
    with open(path) as ext_file:
PermissionError: [Errno 13] Permissio
```

**Comment by suchyta1** [comment]
I've seen this error before, but I don't understand what causes it. You should be able to `rm -r` the directory of what you want to uninstall. And then I think the uninstall sees it as a stale package and it gets removed OK.

**Comment by Damilare06** [comment]
okay, thank you very much. I would do just that

**Comment by suchyta1** [comment]
> Hi Eric, I am running:
> 
> * the `develop` branch of this [coupler](https://github.com/SCOREC/wdmapp_coupling)
> * the `rpi` branch of [this](https://github.com/wdmapp/XGC-Devel) xgc-devel
> * the `rpi` branch of [this](https://github.com/phyboyzhang) gene
> 
> When running the coupler with `Sst` mode, I get this output from the coupler as `xgc` attempts to read from it (before this, the `coupler` has successfully read multiple sst buffers from `gene`).
> 
> Using the `effis` submit setup I got
> 
> ```
>  34 2: receive gene_density done                                                                         | 94 mype, start count2 0 2160 16 2160
>  35 3: receive gene_density done                                                                         | 95 rank=2
>  36 invalid format in incoming buffer                                                                    | 96 ../coupling/gene_density.bp
>  37 ERROR:  One or more process (first noticed rank 0) terminated with signal 12                         | 97 creat engine for: gene_density
> ~                                                                                                        | 98 engine parameters are set
> ~                                                                                                        | 99 Shape 0 1=4320 16
> ~                                                                                                        |100 Shape 0 1=4320 16
> ~                                                                                                        |101 Shape 0 1=4320 16
> ~                                                                                                        |102 Shape 0 1=4320 16
> ~                                                                                                        |103 numiter,ranki densityfromGENE=0 0 (8.82229,-0.0714541)
> ~                                                                                                        |104 p3m3d.lj0*p3m3d.blockcount=1990816
> ~                                                                                                        |105 numiter,ranki densitytoXGC=0 0 259424 1990816
> ~                                                                                                        |106 numiter,ranki densityfromGENE=0 3 (28.0649,-0.0714279)
> ~                                                                                                        |107 p3m3d.lj0*p3m3d.blockcount=5130432
> ~                                                                                                        |108 numiter,ranki densitytoXGC=0 1 543136 5130432
> ~                                                                                                        |109 numiter,ranki densityfromGENE=0 2 (21.4586,0.0714541)
> ~                                                                                                        |110 p3m3d.lj0*p3m3d.blockcount=5130432
> ~                                                                                                        |111 numiter,ranki densitytoXGC=0 1 543136 5130432
> ~                                                                                                        |112 numiter,ranki densityfromGENE=0 1 (11.5387,0.0714279)
> ~                                                                                                        |113 p3m3d.lj0*p3m3d.blockcount=1990816
> ~                                                                                                        |114 numiter,ranki densitytoXGC=0 0 259424 1990816
> codar.workflow.stderr.coupler                                                          1,1            All codar.workflow.stdout.coupler                   
> ```
> 
> Thinking it was an `effis` issue, I switched to a regular submit file and I got the same error
> 
> ```
> 2: 3: p3m3d.lj0*p3m3d.blockcount=5130432                                                                 │1: 0:  background elec charge
> 2: 3: 0.0 ABJ                                                                                            │1: 0:  End of setup
> 2: 3: 0.1 ABJ                                                                                            │1: 0:  main loop started
> 2: 3: 0.2 ABJ                                                                                            │1: 0:  - do loop start
> 2: 3: 0.3 ABJ                                                                                            │1: 0: step,trigger,ratio,# of ion      1     1.1000     1.0000      512000000
> 2: 0: invalid format in incoming buffer                                                                  │1: 0: step,f0(ratio,max)    1    -1.0000     0.0000
> Could not read jskill result from pmix server                                                            │Could not read jskill result from pmix server
>                                                                                                          │
> ```
> 
> The coupler still fails the moment `xgc` connects.
> 
> When I turn on `SstVerbose`, I get this output just before the coupler fails;
> 
> ```
> 529 2: 3: Writer 3 (0x4d531770): Opening Stream "../coupling/cpl_density.bp"
> 5530 2: 3: Writer 3 (0x4d531770): Stream "../coupling/cpl_density.bp" waiting for 1 readers
> 5531 2: 0: Writer 0 (0x454f34e0): Opening Stream "../coupling/cpl_density.bp"
> 5532 2: 0: Writer 0 (0x454f34e0): Writer stream params are:
> 5533 2: 0: Param -   RegistrationMethod=File
> 5534 2: 0: Param -   RendezvousReaderCount=1
> 5535 2: 0: Param -   QueueLimit=0 (unlimited)
> 5536 2: 0: Param -   QueueFullPolicy=Block
> 5537 2: 0: Param -   DataTransport=rdma
> 5538 2: 0: Param -   ControlTransport=sockets
> 5539 2: 0: Param -   NetworkInterface=(default)
> 5540 2: 0: Param -   ControlInterface=(default to NetworkInterface if applicable)
> 5541 2: 0: Param -   DataInterface=(default to NetworkInterface if applicable)
> 5542 2: 0: Param -   CompressionMethod=None
> 5543 2: 0: Param -   CPCommPattern=Min
> 5544 2: 0: Param -   MarshalMethod=BP
> 5545 2: 0: Param -   FirstTimestepPrecious=False
> 5546 2: 0: Param -   IsRowMajor=1  (not user settable)
> 5547 2: 0: Param -   OpenTimeoutSecs=480 (seconds)
> 5548 2: 0: Param -   SpeculativePreloadMode=Auto
> 5549 2: 0: Param -   SpecAutoNodeThreshold=1
> 5550 2: 0: Param -   ControlModule=select
> 5551 2: 0: Writer 0 (0x454f34e0): Stream "../coupling/cpl_density.bp" waiting for 1 readers
> 5552 2: 0: invalid format in incoming buffer
> ```
> 
> Below is a copy of the run scripts I used in both cases
> 
> [runScripts.zip](https://github.com/SCOREC/wdmapp_coupling/files/5075643/runScripts.zip)
> 
> Please note that my post-doc @phyboyzhang can run successfully with the regular job submission.
> 
> Moreover, I run the jobs from a clean terminal with these modules
> 
> ```
> [damilare@login2.summit run_1]$ module li
> 
> Currently Loaded Modules:
>   1) xl/16.1.1-5                      4) xalt/1.2.0              7) DefApps
>   2) spectrum-mpi/10.3.1.2-20200121   5) lsf-tools/2.0           8) tmux/2.2
>   3) hsi/5.0.2.p5                     6) darshan-runtime/3.1.7   9) git/2.20.1
> ```
> 
> Your help would be appreciated

BTW, I'm trying to look deeper into what's going on. I didn't see anything immediately obvious.

**Comment by Damilare06** [comment]
I cannot `rm -rf` the directory 
```
rm: cannot remove 'python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/lib/python3.7/__pycache__/uu.cpython-37.opt-2.pyc': Permission denied
rm: cannot remove 'python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/lib/python3.7/__pycache__/uuid.cpython-37.opt-2.pyc': Permission denied
rm: cannot remove 'python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/lib/python3.7/__pycache__/warnings.cpython-37.opt-2.pyc': Permission denied
rm: cannot remove 'python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/lib/python3.7/__pycache__/wave.cpython-37.opt-2.pyc': Permission denied
rm: cannot remove 'python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/lib/python3.7/__pycache__/webbrowser.cpython-37.opt-2.pyc': Permission denied
rm: cannot remove 'python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/lib/python3.7/__pycache__/xdrlib.cpython-37.opt-2.pyc': Permission denied
rm: cannot remove 'python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/lib/python3.7/__pycache__/zipapp.cpython-37.opt-2.pyc': Permission denied
rm: cannot remove 'python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/lib/python3.7/__pycache__/zipfile.cpython-37.opt-2.pyc': Permission denied
rm: cannot remove 'python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/lib/libpython3.7m.so.1.0': Permission denied
rm: cannot remove 'python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/lib/libpython3.7m.so': Permission denied
rm: cannot remove 'python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/lib/libpython3.so': Permission denied
rm: cannot remove 'python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/lib/pkgconfig/python-3.7m.pc': Permission denied
rm: cannot remove 'python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/lib/pkgconfig/python3.pc': Permission denied
rm: cannot remove 'python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/lib/pkgconfig/python-3.7.pc': Permission denied
rm: cannot remove 'python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/share/man/man1/python3.7.1': Permission denied
rm: cannot remove 'python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/share/man/man1/python3.1': Permission denied
rm: cannot remove 'python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/man/man1/nosetests.1': Permission denied
[damilare@login2.summit gcc-4.8.5]$ 
```

**Comment by Damilare06** [comment]
I am attempting to clear out my spack and start afresh (Reinstall everything) but this error is preventing me.

Do you know any alternative way to reinstall spack nd everything

**Comment by suchyta1** [comment]
Can you try commenting out the `extends` line in the EFFIS spack package. Sometimes I've needed that on Summit.

**Comment by suchyta1** [comment]
And above, you should be able to `rm -r` the things in your area, not the external packages. Your `pwd` is a system area for the python install.

**Comment by Damilare06** [comment]
spack returns that path as the path to an installed python package
```
[damilare@login2.summit gcc-4.8.5]$ spack find
==> 54 installed packages
-- linux-rhel7-power9le / gcc@8.1.1 -----------------------------
adios2@2.6.0           effis@develop    libdwarf@20180129    libpciaccess@0.13.5  metis@5.1.0             py-cycler@0.10.0     py-pillow@7.0.0           py-six@1.12.0                   sz@2.0.2.0
bzip2@1.0.8            expat@2.2.9      libelf@0.8.13        libpng@1.6.37        netlib-scalapack@2.1.0  py-cython@0.29.14    py-pyparsing@2.4.2        python@3.7.0                    xz@5.2.4
c-blosc@1.17.0         fftw@3.3.8       libfabric@1.9.0      libsigsegv@2.12      openblas@0.3.8          py-kiwisolver@1.1.0  py-python-dateutil@2.8.0  rdma-core@20                    yaml-cpp@0.6.3
camtimers@0.1.0        freetype@2.10.1  libffi@3.0.13        libsodium@1.0.18     openssl@1.0.2k          py-matplotlib@3.1.3  py-pyyaml@5.1.2           snappy@1.1.0                    zfp@0.5.5
cmake@3.16.2           hypre@2.13.0     libiconv@1.16        libyaml@0.2.2        parmetis@4.0.3          py-mpi4py@3.0.3      py-setuptools@41.4.0      spectrum-mpi@10.3.1.2-20200121  zlib@1.2.7
codar-cheetah@develop  libbsd@0.10.0    libjpeg-turbo@2.0.3  libzmq@4.3.2         pspline@0.1.0           py-numpy@1.18.1      py-setuptools-scm@3.3.3   superlu-dist@5.1.3              zstd@1.4.3
[damilare@login2.summit gcc-4.8.5]$ spack find --path python@3.7.0
==> 1 installed package
-- linux-rhel7-power9le / gcc@8.1.1 -----------------------------
python@3.7.0  /autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn
[damilare@login2.summit gcc-4.8.5]$ 
```

**Comment by Damilare06** [comment]
I have been able to rm -rf within spack. Id start afresh now. Thanks
