### ISSUE TITLE
-DPERFSTUBS_USE_TIMERS FLAG

### ISSUE THREAD

**Issue by Damilare06** [SCOREC/wdmapp_coupling#94]
I have a coupler `perfstubs` branch that contains the instrumentation needed to time routines and but would need the flag `-DPERFSTUBS_USE_TIMERS=ON`. To use simple `spack install` command you suggested, I modified my coupler packages.py and set it up [here](https://github.com/Damilare06/wdmapp-config/blob/3d46cbb114f7f2ed01fa5ee09e0df6b31dbb3fab/spack/wdmapp/packages/coupler/package.py).

I can build other branches correctly by switching my git URL to the SCOREC version.

It builds the coupler `perfstubs` branch and it runs smoothly but doesn't seem to turn ON the flag as the `tau` visualization results from the run do not show any instrumented functions -  alluding to the flag being turned off.

What is the spack fix to get this working?

**Comment by jacobmerson** [comment]
Closing due to coupler rewrite.
